/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportSizingRouteImport } from './routes/support.sizing'
import { Route as SupportShippingRouteImport } from './routes/support.shipping'
import { Route as SupportReturnsRouteImport } from './routes/support.returns'
import { Route as SupportContactRouteImport } from './routes/support.contact'
import { Route as StudioPressRouteImport } from './routes/studio.press'
import { Route as StudioManifestoRouteImport } from './routes/studio.manifesto'
import { Route as StudioLookbookRouteImport } from './routes/studio.lookbook'
import { Route as StudioJournalRouteImport } from './routes/studio.journal'
import { Route as ShopOuterwearRouteImport } from './routes/shop.outerwear'
import { Route as ShopModularRouteImport } from './routes/shop.modular'
import { Route as ShopLayersRouteImport } from './routes/shop.layers'
import { Route as ShopBottomsRouteImport } from './routes/shop.bottoms'
import { Route as ShopArchiveRouteImport } from './routes/shop.archive'

const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportSizingRoute = SupportSizingRouteImport.update({
  id: '/support/sizing',
  path: '/support/sizing',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportShippingRoute = SupportShippingRouteImport.update({
  id: '/support/shipping',
  path: '/support/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportReturnsRoute = SupportReturnsRouteImport.update({
  id: '/support/returns',
  path: '/support/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportContactRoute = SupportContactRouteImport.update({
  id: '/support/contact',
  path: '/support/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioPressRoute = StudioPressRouteImport.update({
  id: '/studio/press',
  path: '/studio/press',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioManifestoRoute = StudioManifestoRouteImport.update({
  id: '/studio/manifesto',
  path: '/studio/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioLookbookRoute = StudioLookbookRouteImport.update({
  id: '/studio/lookbook',
  path: '/studio/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioJournalRoute = StudioJournalRouteImport.update({
  id: '/studio/journal',
  path: '/studio/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopOuterwearRoute = ShopOuterwearRouteImport.update({
  id: '/shop/outerwear',
  path: '/shop/outerwear',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopModularRoute = ShopModularRouteImport.update({
  id: '/shop/modular',
  path: '/shop/modular',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopLayersRoute = ShopLayersRouteImport.update({
  id: '/shop/layers',
  path: '/shop/layers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopBottomsRoute = ShopBottomsRouteImport.update({
  id: '/shop/bottoms',
  path: '/shop/bottoms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopArchiveRoute = ShopArchiveRouteImport.update({
  id: '/shop/archive',
  path: '/shop/archive',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/shop/archive': typeof ShopArchiveRoute
  '/shop/bottoms': typeof ShopBottomsRoute
  '/shop/layers': typeof ShopLayersRoute
  '/shop/modular': typeof ShopModularRoute
  '/shop/outerwear': typeof ShopOuterwearRoute
  '/studio/journal': typeof StudioJournalRoute
  '/studio/lookbook': typeof StudioLookbookRoute
  '/studio/manifesto': typeof StudioManifestoRoute
  '/studio/press': typeof StudioPressRoute
  '/support/contact': typeof SupportContactRoute
  '/support/returns': typeof SupportReturnsRoute
  '/support/shipping': typeof SupportShippingRoute
  '/support/sizing': typeof SupportSizingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/shop/archive': typeof ShopArchiveRoute
  '/shop/bottoms': typeof ShopBottomsRoute
  '/shop/layers': typeof ShopLayersRoute
  '/shop/modular': typeof ShopModularRoute
  '/shop/outerwear': typeof ShopOuterwearRoute
  '/studio/journal': typeof StudioJournalRoute
  '/studio/lookbook': typeof StudioLookbookRoute
  '/studio/manifesto': typeof StudioManifestoRoute
  '/studio/press': typeof StudioPressRoute
  '/support/contact': typeof SupportContactRoute
  '/support/returns': typeof SupportReturnsRoute
  '/support/shipping': typeof SupportShippingRoute
  '/support/sizing': typeof SupportSizingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/shop/archive': typeof ShopArchiveRoute
  '/shop/bottoms': typeof ShopBottomsRoute
  '/shop/layers': typeof ShopLayersRoute
  '/shop/modular': typeof ShopModularRoute
  '/shop/outerwear': typeof ShopOuterwearRoute
  '/studio/journal': typeof StudioJournalRoute
  '/studio/lookbook': typeof StudioLookbookRoute
  '/studio/manifesto': typeof StudioManifestoRoute
  '/studio/press': typeof StudioPressRoute
  '/support/contact': typeof SupportContactRoute
  '/support/returns': typeof SupportReturnsRoute
  '/support/shipping': typeof SupportShippingRoute
  '/support/sizing': typeof SupportSizingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/checkout'
    | '/shop/archive'
    | '/shop/bottoms'
    | '/shop/layers'
    | '/shop/modular'
    | '/shop/outerwear'
    | '/studio/journal'
    | '/studio/lookbook'
    | '/studio/manifesto'
    | '/studio/press'
    | '/support/contact'
    | '/support/returns'
    | '/support/shipping'
    | '/support/sizing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/checkout'
    | '/shop/archive'
    | '/shop/bottoms'
    | '/shop/layers'
    | '/shop/modular'
    | '/shop/outerwear'
    | '/studio/journal'
    | '/studio/lookbook'
    | '/studio/manifesto'
    | '/studio/press'
    | '/support/contact'
    | '/support/returns'
    | '/support/shipping'
    | '/support/sizing'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/checkout'
    | '/shop/archive'
    | '/shop/bottoms'
    | '/shop/layers'
    | '/shop/modular'
    | '/shop/outerwear'
    | '/studio/journal'
    | '/studio/lookbook'
    | '/studio/manifesto'
    | '/studio/press'
    | '/support/contact'
    | '/support/returns'
    | '/support/shipping'
    | '/support/sizing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CheckoutRoute: typeof CheckoutRoute
  ShopArchiveRoute: typeof ShopArchiveRoute
  ShopBottomsRoute: typeof ShopBottomsRoute
  ShopLayersRoute: typeof ShopLayersRoute
  ShopModularRoute: typeof ShopModularRoute
  ShopOuterwearRoute: typeof ShopOuterwearRoute
  StudioJournalRoute: typeof StudioJournalRoute
  StudioLookbookRoute: typeof StudioLookbookRoute
  StudioManifestoRoute: typeof StudioManifestoRoute
  StudioPressRoute: typeof StudioPressRoute
  SupportContactRoute: typeof SupportContactRoute
  SupportReturnsRoute: typeof SupportReturnsRoute
  SupportShippingRoute: typeof SupportShippingRoute
  SupportSizingRoute: typeof SupportSizingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/sizing': {
      id: '/support/sizing'
      path: '/support/sizing'
      fullPath: '/support/sizing'
      preLoaderRoute: typeof SupportSizingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/shipping': {
      id: '/support/shipping'
      path: '/support/shipping'
      fullPath: '/support/shipping'
      preLoaderRoute: typeof SupportShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/returns': {
      id: '/support/returns'
      path: '/support/returns'
      fullPath: '/support/returns'
      preLoaderRoute: typeof SupportReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/contact': {
      id: '/support/contact'
      path: '/support/contact'
      fullPath: '/support/contact'
      preLoaderRoute: typeof SupportContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/press': {
      id: '/studio/press'
      path: '/studio/press'
      fullPath: '/studio/press'
      preLoaderRoute: typeof StudioPressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/manifesto': {
      id: '/studio/manifesto'
      path: '/studio/manifesto'
      fullPath: '/studio/manifesto'
      preLoaderRoute: typeof StudioManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/lookbook': {
      id: '/studio/lookbook'
      path: '/studio/lookbook'
      fullPath: '/studio/lookbook'
      preLoaderRoute: typeof StudioLookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/journal': {
      id: '/studio/journal'
      path: '/studio/journal'
      fullPath: '/studio/journal'
      preLoaderRoute: typeof StudioJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/outerwear': {
      id: '/shop/outerwear'
      path: '/shop/outerwear'
      fullPath: '/shop/outerwear'
      preLoaderRoute: typeof ShopOuterwearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/modular': {
      id: '/shop/modular'
      path: '/shop/modular'
      fullPath: '/shop/modular'
      preLoaderRoute: typeof ShopModularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/layers': {
      id: '/shop/layers'
      path: '/shop/layers'
      fullPath: '/shop/layers'
      preLoaderRoute: typeof ShopLayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/bottoms': {
      id: '/shop/bottoms'
      path: '/shop/bottoms'
      fullPath: '/shop/bottoms'
      preLoaderRoute: typeof ShopBottomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/archive': {
      id: '/shop/archive'
      path: '/shop/archive'
      fullPath: '/shop/archive'
      preLoaderRoute: typeof ShopArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CheckoutRoute: CheckoutRoute,
  ShopArchiveRoute: ShopArchiveRoute,
  ShopBottomsRoute: ShopBottomsRoute,
  ShopLayersRoute: ShopLayersRoute,
  ShopModularRoute: ShopModularRoute,
  ShopOuterwearRoute: ShopOuterwearRoute,
  StudioJournalRoute: StudioJournalRoute,
  StudioLookbookRoute: StudioLookbookRoute,
  StudioManifestoRoute: StudioManifestoRoute,
  StudioPressRoute: StudioPressRoute,
  SupportContactRoute: SupportContactRoute,
  SupportReturnsRoute: SupportReturnsRoute,
  SupportShippingRoute: SupportShippingRoute,
  SupportSizingRoute: SupportSizingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
